# Python Quiz EngOrabi

## 1- Create a 5×5 matrix with random integers from 1–100. Replace all values greater than 50 with 0.

In [4]:
import numpy as np
arr = np.random.randint(1, 100, (5, 5))
arr[arr > 50] = 0
print(arr)


[[ 0  0 13 25 30]
 [17  0 39 31  0]
 [ 0 44  0 49  0]
 [20  0 16  0  0]
 [25  0 10  0  0]]


## 2- Generate a 1D NumPy array of 50 random integers (1–100). Find the mean, median, variance, and standard deviation.

In [7]:
arr = np.random.randint(1, 100,size=50 )
median_val = np.median(arr) 
var_val = np.var(arr)        
std_val = np.std(arr)   
print(median_val)
print(var_val)  
print(std_val)


61.5
911.2624000000001
30.187123082533056


## 3- Create two arrays of shape (5,). Stack them into a 2D array Vertically and Horizntally

In [8]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
v_stack = np.vstack((a, b))
print(v_stack)
h_stack = np.column_stack((a, b))
print(h_stack)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


## 4-Create two arrays of any shape and stack them vertically and Horizontally

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])
v_stack = np.vstack((a, b))
print(v_stack)
h_stack = np.column_stack((a, b))
print(h_stack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## 5- Create a 7×7 matrix with random integers. Extract the first row, last row, first column, and last column.

In [12]:
import numpy as np

arr = np.random.randint(1, 101, size=(7, 7))
first_row = arr[0]      
last_row = arr[-1]      
first_col = arr[:, 0]    
last_col = arr[:, -1] 

print(arr)
print("First row:", first_row)
print("Last row:", last_row)
print("First column:", first_col)
print("Last column:", last_col)


[[99  1 82 46 29 37 67]
 [12 30 64 68 16 50 33]
 [56 89 29 77 10 25 42]
 [93  3 97 30 46 41 55]
 [ 8  9 14 33 50 16 88]
 [33 21  5 38 90 35 29]
 [43 66 69 34  9 15 42]]
First row: [99  1 82 46 29 37 67]
Last row: [43 66 69 34  9 15 42]
First column: [99 12 56 93  8 33 43]
Last column: [67 33 42 55 88 29 42]


## 6- Create a 1D array of 15 random integers.Find the elements greater than the mean.

In [17]:
arr = np.random.randint(1, 101, size=15)
mean_val = np.mean(arr)
greater_than_mean = arr[arr > mean_val]

print(arr)
print("Mean:", mean_val)
print("Numbers bigger than the mean:", greater_than_mean)

[14 98  6 62 26 17 37  2 75 94 96 84 23 37 39]
Mean: 47.333333333333336
Numbers bigger than the mean: [98 62 75 94 96 84]


## 7- Load the Titanic dataset inside seaborn and print the information and statistical of the dataset "titanic"

In [ ]:
import seaborn as sns
import pandas as pd

titanic = sns.load_dataset("titanic")

df = df.info()
df = df.info()

print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alo

## 8- Show the distribution of survival rate by gender and class using a grouped bar chart.

## 9- Plot the distribution of ages for survivors vs non-survivors using a KDE plot. Comment on whether younger passengers had higher survival chances.

## 10- Show the number of passengers from each embarkation port (embarked).Plot their survival rate using a bar chart.

## 11- Create a new column family_size = sibsp + parch + 1. Find the average survival rate by family size.

## 12- Find the rows of the passengers who paid the highest fare

## 13- Compute survival rate for each embarkation port (embarked) with two aggregation functions mean and counnt

## 14- Show a crosstab of passenger counts by sex and pclass.

## 15-Select all passengers who are female and traveled in class 1st. From this subset, further filter those whose age is less than 30.

## 16-Select all passengers who either paid a fare > 100 or were in "First" class. From the result, remove passengers whose embarked port was "Q"

## 17- sort the Titanic passengers: First by pclass in ascending order. Then by fare in descending order on one line code do not make them individual

## 18- Rank passengers within each passenger class (pclass) separately based on their (fare).

## 19- Preprocessing Questions Get this Dataset import it and get ready for the next questions  [link Data](https://drive.google.com/file/d/1Vb_JqIVM0Gy47_JXiTUIROVpd6ylOy7a/view?usp=sharing)

## 20- Handle Missing Values
### 1- Identify which columns contain missing values.
### 2- Decide for each type of feature (numerical / categorical) how to fill missing values.
### 3- Justify why you used this method.

## 21. Encode Categorical Variables
### 1- Detect all categorical features (e.g., Gender, loan_type, loan_purpose, Region, Security_Type, etc.).
### 2- Choose an appropriate encoding method for each column:
### 3- Nominal categorical features (no ranking between categories).
### 4- Ordinal categorical features (if categories have an order).
### 5- After encoding, check the number of features and explain if the dimensionality increased.

## 22. Feature Scaling
### 1- Select numeric features (e.g., Credit_Score, dtir1, LTV, etc.).
### 2- Apply a scaling method of your choice (e.g., StandardScaler, MinMaxScaler, or others).
### 3- Explain why you chose this method.
### 4- Make sure scaling is applied correctly without causing data leakage.

## 23- Handle Class Imbalance
### 1-Check the distribution of the target column (Status).
### 2-If the dataset is imbalanced, apply a suitable technique to balance the data
### 3- Compare class distribution before and after handling imbalance.

## 24- Train-Test Split
### 1- Split the dataset into train (80%) and test (20%) sets.
### 2- Make sure that transformations and scaling are fitted only on training data and applied to test data separately.